package com.zapbot.android.ui

import com.zapbot.android.domain.LanguageResolver

object AppStrings {
    fun label(language: String, key: String): String = when (LanguageResolver.resolve(language)) {
        "pt" -> pt[key]
        "es" -> es[key]
        "ru" -> ru[key]
        else -> en[key]
    } ?: en[key] ?: key

    private val en = mapOf(
        "settings" to "Settings",
        "settings_subtitle" to "Control WhatsApp, bot behavior, downloads, network use, and app preferences.",
        "preferences" to "Preferences",
        "preferences_desc" to "Theme, languages, and connection rules used by the app and bot.",
        "automation" to "Automation",
        "automation_desc" to "Startup, notifications, and Android battery behavior.",
        "whatsapp_section_desc" to "Pair this phone as a WhatsApp linked device and manage the saved session.",
        "downloads_desc" to "Tune performance and media quality for downloads sent through WhatsApp.",
        "simultaneous_downloads" to "Simultaneous downloads",
        "start_boot_desc" to "Start the bot automatically after the phone restarts.",
        "notifications_desc" to "Keep the foreground service visible while the bot is active.",
        "detailed_notifications_desc" to "Show extra download status in Android notifications.",
        "appearance" to "Appearance",
        "app_language" to "App language",
        "bot_language" to "Bot message language",
        "system_language" to "System language",
        "network_preference" to "Network preference",
        "wifi_only" to "Wi-Fi only",
        "any_network" to "Any network",
        "any_network_warning" to "Warning: allowing the bot to run on any network can quickly consume your mobile data. Confirm?",
        "mobile_start_warning" to "You are on mobile data. Do you want to start the bot and use your mobile internet?",
        "start_requires_whatsapp" to "Connect WhatsApp in Settings before starting the bot.",
        "start_anyway" to "Start anyway",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "about" to "About",
        "developer" to "Developer",
        "version" to "Version",
        "check_updates" to "Check for updates",
        "checking_updates" to "Checking...",
        "updates_placeholder" to "Update checking is not configured yet.",
        "battery" to "Open battery settings",
        "downloads" to "Simultaneous downloads",
        "quality" to "Video quality",
        "audio" to "Audio",
        "clear_cache" to "Clear WhatsApp cache",
        "logs" to "Logs",
        "home" to "Home",
        "jobs" to "Jobs",
        "errors" to "Recent errors",
        "subtitle" to "WhatsApp automation console",
        "start_bot" to "Start bot",
        "stop_bot" to "Stop bot",
        "bot_status" to "Bot status",
        "disconnected" to "Disconnected",
        "waiting_qr" to "Waiting for QR code",
        "connecting" to "Connecting",
        "connected" to "Connected",
        "running" to "Running",
        "last_error" to "Last error",
        "active" to "Active",
        "uptime" to "Uptime",
        "today" to "Today",
        "messages" to "Messages",
        "searches" to "Searches",
        "completed" to "Completed",
        "failed" to "Failed",
        "no_jobs" to "No jobs created.",
        "time" to "Time",
        "chat" to "Chat",
        "clear" to "Clear",
        "whatsapp_integration" to "WhatsApp integration",
        "session_saved" to "OK - WhatsApp session saved",
        "session_running" to "This bot already has a saved WhatsApp session and is running.",
        "session_disconnected" to "This bot already has a saved WhatsApp session. Start the bot to connect.",
        "session_saved_detail" to "This bot already has a saved WhatsApp session.",
        "pairing_intro" to "This bot connects as a real linked device for your personal WhatsApp account. Enter the number from the main phone, then approve the code in WhatsApp > Linked devices.",
        "whatsapp_number" to "WhatsApp number",
        "generate_again" to "Generate again in",
        "generate_code" to "Generate Linked Devices code",
        "code" to "Code",
        "copy_code" to "Copy code",
        "tap_copy" to "Tap the code to copy it.",
        "link_phone" to "In WhatsApp: Linked devices > Link with phone number.",
        "regular_messages" to "Regular messages are ignored silently. The bot only replies to slash commands such as /help, /music search, /v, /a, /status, and /cancel.",
        "blacklist" to "Blocklist",
        "blacklist_desc" to "Numbers listed here are ignored by the bot. The app stays connected to WhatsApp, but the bot will not search, download, or reply to those people.",
        "blocklist_new_number" to "WhatsApp number",
        "add_blocklist_number" to "Add",
        "remove_blocklist_number" to "Remove number",
        "blocklist_empty" to "No blocked numbers yet.",
        "blocklist_active_numbers" to "Blocked numbers",
        "start_boot" to "Start when the phone boots",
        "notifications" to "Notifications",
        "detailed_notifications" to "Detailed notifications",
        "system" to "System",
        "light" to "Light",
        "dark" to "Dark",
        "video" to "Video",
        "audio_type" to "Audio",
        "queued" to "Queued",
        "downloading" to "Downloading",
        "processing" to "Processing",
        "sending" to "Sending",
        "cancelled" to "Cancelled",
        "no_logs" to "No bot logs yet.",
        "no_errors" to "No recent errors."
    )
    private val pt = mapOf(
        "settings" to "Ajustes",
        "settings_subtitle" to "Controle WhatsApp, comportamento do bot, downloads, rede e preferências do app.",
        "preferences" to "Preferências",
        "preferences_desc" to "Tema, idiomas e regras de conexão usadas pelo app e pelo bot.",
        "automation" to "Automação",
        "automation_desc" to "Inicialização, notificações e comportamento de bateria do Android.",
        "whatsapp_section_desc" to "Vincule este celular como aparelho conectado do WhatsApp e gerencie a sessão salva.",
        "downloads_desc" to "Ajuste desempenho e qualidade das mídias enviadas pelo WhatsApp.",
        "simultaneous_downloads" to "Downloads simultâneos",
        "start_boot_desc" to "Inicia o bot automaticamente depois que o celular reiniciar.",
        "notifications_desc" to "Mantém o serviço em primeiro plano visível enquanto o bot está ativo.",
        "detailed_notifications_desc" to "Mostra status extra dos downloads nas notificações do Android.",
        "appearance" to "Aparência",
        "app_language" to "Idioma do aplicativo",
        "bot_language" to "Idioma das mensagens do bot",
        "system_language" to "Idioma do sistema",
        "network_preference" to "Preferência de rede",
        "wifi_only" to "Apenas Wi-Fi",
        "any_network" to "Qualquer rede",
        "any_network_warning" to "Aviso: permitir o funcionamento em qualquer rede pode consumir rapidamente sua internet móvel. Confirmar?",
        "mobile_start_warning" to "Você está nos dados móveis. Deseja ligar o bot e usar sua internet móvel?",
        "start_requires_whatsapp" to "Conecte o WhatsApp nos Ajustes antes de iniciar o bot.",
        "start_anyway" to "Ligar mesmo assim",
        "confirm" to "Confirmar",
        "cancel" to "Cancelar",
        "about" to "Sobre",
        "developer" to "Desenvolvedor",
        "version" to "Versão",
        "check_updates" to "Verificar atualizações",
        "checking_updates" to "Verificando...",
        "updates_placeholder" to "A verificação de atualizações ainda não está configurada.",
        "battery" to "Abrir configurações de bateria",
        "downloads" to "Downloads simultâneos",
        "quality" to "Qualidade do vídeo",
        "audio" to "Áudio",
        "clear_cache" to "Limpar cache do WhatsApp",
        "logs" to "Logs",
        "home" to "Início",
        "jobs" to "Tarefas",
        "errors" to "Erros recentes",
        "subtitle" to "Painel de automação do WhatsApp",
        "start_bot" to "Iniciar bot",
        "stop_bot" to "Parar bot",
        "bot_status" to "Status do bot",
        "disconnected" to "Desconectado",
        "waiting_qr" to "Aguardando QR code",
        "connecting" to "Conectando",
        "connected" to "Conectado",
        "running" to "Rodando",
        "last_error" to "Último erro",
        "active" to "Ativos",
        "uptime" to "Tempo online",
        "today" to "Hoje",
        "messages" to "Mensagens",
        "searches" to "Buscas",
        "completed" to "Concluídos",
        "failed" to "Falhas",
        "no_jobs" to "Nenhuma tarefa criada.",
        "time" to "Hora",
        "chat" to "Chat",
        "clear" to "Limpar",
        "whatsapp_integration" to "Integração do WhatsApp",
        "session_saved" to "OK - sessão do WhatsApp salva",
        "session_running" to "Este bot já tem uma sessão do WhatsApp salva e está rodando.",
        "session_disconnected" to "Este bot já tem uma sessão do WhatsApp salva. Inicie o bot para conectar.",
        "session_saved_detail" to "Este bot já tem uma sessão do WhatsApp salva.",
        "pairing_intro" to "Este bot conecta como um aparelho vinculado real da sua conta pessoal do WhatsApp. Digite o número do celular principal e aprove o código em WhatsApp > Aparelhos conectados.",
        "whatsapp_number" to "Número do WhatsApp",
        "generate_again" to "Gerar novamente em",
        "generate_code" to "Gerar código de Aparelhos conectados",
        "code" to "Código",
        "copy_code" to "Copiar código",
        "tap_copy" to "Toque no código para copiar.",
        "link_phone" to "No WhatsApp: Aparelhos conectados > Conectar com número de telefone.",
        "regular_messages" to "Mensagens normais são ignoradas silenciosamente. O bot responde apenas a comandos como /help, /music search, /v, /a, /status e /cancel.",
        "blacklist" to "Blocklist",
        "blacklist_desc" to "Os números listados aqui são ignorados pelo bot. O app continua conectado ao WhatsApp, mas o bot não pesquisa, não baixa e não responde essas pessoas.",
        "blocklist_new_number" to "Número do WhatsApp",
        "add_blocklist_number" to "Adicionar",
        "remove_blocklist_number" to "Remover número",
        "blocklist_empty" to "Nenhum número bloqueado ainda.",
        "blocklist_active_numbers" to "Números bloqueados",
        "start_boot" to "Iniciar quando o celular ligar",
        "notifications" to "Notificações",
        "detailed_notifications" to "Notificações detalhadas",
        "system" to "Sistema",
        "light" to "Claro",
        "dark" to "Escuro",
        "video" to "Vídeo",
        "audio_type" to "Áudio",
        "queued" to "Na fila",
        "downloading" to "Baixando",
        "processing" to "Processando",
        "sending" to "Enviando",
        "cancelled" to "Cancelado",
        "no_logs" to "Nenhum log do bot ainda.",
        "no_errors" to "Nenhum erro recente."
    )
    private val es = mapOf(
        "settings" to "Ajustes",
        "settings_subtitle" to "Controla WhatsApp, comportamiento del bot, descargas, red y preferencias de la app.",
        "preferences" to "Preferencias",
        "preferences_desc" to "Tema, idiomas y reglas de conexión usadas por la app y el bot.",
        "automation" to "Automatización",
        "automation_desc" to "Inicio, notificaciones y comportamiento de batería de Android.",
        "whatsapp_section_desc" to "Vincula este teléfono como dispositivo conectado de WhatsApp y gestiona la sesión guardada.",
        "downloads_desc" to "Ajusta rendimiento y calidad de los medios enviados por WhatsApp.",
        "simultaneous_downloads" to "Descargas simultáneas",
        "start_boot_desc" to "Inicia el bot automáticamente después de reiniciar el teléfono.",
        "notifications_desc" to "Mantiene visible el servicio en primer plano mientras el bot está activo.",
        "detailed_notifications_desc" to "Muestra estado extra de las descargas en las notificaciones de Android.",
        "appearance" to "Apariencia",
        "app_language" to "Idioma de la app",
        "bot_language" to "Idioma de mensajes del bot",
        "system_language" to "Idioma del sistema",
        "network_preference" to "Preferencia de red",
        "wifi_only" to "Solo Wi-Fi",
        "any_network" to "Cualquier red",
        "any_network_warning" to "Aviso: permitir el funcionamiento en cualquier red puede consumir rápidamente tus datos móviles. ¿Confirmar?",
        "mobile_start_warning" to "Estás usando datos móviles. ¿Quieres iniciar el bot y usar tu internet móvil?",
        "start_requires_whatsapp" to "Conecta WhatsApp en Ajustes antes de iniciar el bot.",
        "start_anyway" to "Iniciar igual",
        "confirm" to "Confirmar",
        "cancel" to "Cancelar",
        "about" to "Acerca",
        "developer" to "Desarrollador",
        "version" to "Versión",
        "check_updates" to "Buscar actualizaciones",
        "checking_updates" to "Buscando...",
        "updates_placeholder" to "La búsqueda de actualizaciones aún no está configurada.",
        "battery" to "Abrir ajustes de batería",
        "downloads" to "Descargas simultáneas",
        "quality" to "Calidad de video",
        "audio" to "Audio",
        "clear_cache" to "Limpiar caché de WhatsApp",
        "logs" to "Registros",
        "home" to "Inicio",
        "jobs" to "Tareas",
        "errors" to "Errores recientes",
        "subtitle" to "Panel de automatización de WhatsApp",
        "start_bot" to "Iniciar bot",
        "stop_bot" to "Detener bot",
        "bot_status" to "Estado del bot",
        "disconnected" to "Desconectado",
        "waiting_qr" to "Esperando QR",
        "connecting" to "Conectando",
        "connected" to "Conectado",
        "running" to "Activo",
        "last_error" to "Último error",
        "active" to "Activos",
        "uptime" to "Tiempo activo",
        "today" to "Hoy",
        "messages" to "Mensajes",
        "searches" to "Búsquedas",
        "completed" to "Completados",
        "failed" to "Fallos",
        "no_jobs" to "No hay tareas creadas.",
        "time" to "Hora",
        "chat" to "Chat",
        "clear" to "Limpiar",
        "whatsapp_integration" to "Integración de WhatsApp",
        "session_saved" to "OK - sesión de WhatsApp guardada",
        "session_running" to "Este bot ya tiene una sesión de WhatsApp guardada y está activo.",
        "session_disconnected" to "Este bot ya tiene una sesión de WhatsApp guardada. Inicia el bot para conectar.",
        "session_saved_detail" to "Este bot ya tiene una sesión de WhatsApp guardada.",
        "pairing_intro" to "Este bot se conecta como un dispositivo vinculado real de tu cuenta personal de WhatsApp. Ingresa el número del teléfono principal y aprueba el código en WhatsApp > Dispositivos vinculados.",
        "whatsapp_number" to "Número de WhatsApp",
        "generate_again" to "Generar de nuevo en",
        "generate_code" to "Generar código de dispositivos vinculados",
        "code" to "Código",
        "copy_code" to "Copiar código",
        "tap_copy" to "Toca el código para copiarlo.",
        "link_phone" to "En WhatsApp: Dispositivos vinculados > Vincular con número de teléfono.",
        "regular_messages" to "Los mensajes normales se ignoran silenciosamente. El bot solo responde a comandos como /help, /music search, /v, /a, /status y /cancel.",
        "blacklist" to "Blocklist",
        "blacklist_desc" to "Los números listados aquí son ignorados por el bot. La app sigue conectada a WhatsApp, pero el bot no busca, no descarga ni responde a esas personas.",
        "blocklist_new_number" to "Número de WhatsApp",
        "add_blocklist_number" to "Agregar",
        "remove_blocklist_number" to "Eliminar número",
        "blocklist_empty" to "Aún no hay números bloqueados.",
        "blocklist_active_numbers" to "Números bloqueados",
        "start_boot" to "Iniciar al encender el teléfono",
        "notifications" to "Notificaciones",
        "detailed_notifications" to "Notificaciones detalladas",
        "system" to "Sistema",
        "light" to "Claro",
        "dark" to "Oscuro",
        "video" to "Video",
        "audio_type" to "Audio",
        "queued" to "En cola",
        "downloading" to "Descargando",
        "processing" to "Procesando",
        "sending" to "Enviando",
        "cancelled" to "Cancelado",
        "no_logs" to "Aún no hay registros del bot.",
        "no_errors" to "No hay errores recientes."
    )
    private val ru = mapOf(
        "settings" to "Настройки",
        "settings_subtitle" to "Управление WhatsApp, поведением бота, загрузками, сетью и настройками приложения.",
        "preferences" to "Предпочтения",
        "preferences_desc" to "Тема, языки и правила подключения для приложения и бота.",
        "automation" to "Автоматизация",
        "automation_desc" to "Автозапуск, уведомления и поведение батареи Android.",
        "whatsapp_section_desc" to "Подключите телефон как связанное устройство WhatsApp и управляйте сохраненной сессией.",
        "downloads_desc" to "Настройте производительность и качество медиа для отправки через WhatsApp.",
        "simultaneous_downloads" to "Одновременные загрузки",
        "start_boot_desc" to "Автоматически запускает бот после перезагрузки телефона.",
        "notifications_desc" to "Показывает активный foreground-сервис, пока бот работает.",
        "detailed_notifications_desc" to "Показывает дополнительный статус загрузок в уведомлениях Android.",
        "appearance" to "Внешний вид",
        "app_language" to "Язык приложения",
        "bot_language" to "Язык сообщений бота",
        "system_language" to "Язык системы",
        "network_preference" to "Предпочтение сети",
        "wifi_only" to "Только Wi-Fi",
        "any_network" to "Любая сеть",
        "any_network_warning" to "Внимание: работа в любой сети может быстро расходовать мобильный интернет. Подтвердить?",
        "mobile_start_warning" to "Вы используете мобильный интернет. Запустить бот и использовать мобильные данные?",
        "start_requires_whatsapp" to "Подключите WhatsApp в настройках перед запуском бота.",
        "start_anyway" to "Запустить",
        "confirm" to "Подтвердить",
        "cancel" to "Отмена",
        "about" to "О приложении",
        "developer" to "Разработчик",
        "version" to "Версия",
        "check_updates" to "Проверить обновления",
        "checking_updates" to "Проверка...",
        "updates_placeholder" to "Проверка обновлений пока не настроена.",
        "battery" to "Открыть настройки батареи",
        "downloads" to "Одновременные загрузки",
        "quality" to "Качество видео",
        "audio" to "Аудио",
        "clear_cache" to "Очистить кэш WhatsApp",
        "logs" to "Журналы",
        "home" to "Главная",
        "jobs" to "Задачи",
        "errors" to "Последние ошибки",
        "subtitle" to "Панель автоматизации WhatsApp",
        "start_bot" to "Запустить бот",
        "stop_bot" to "Остановить бот",
        "bot_status" to "Статус бота",
        "disconnected" to "Отключен",
        "waiting_qr" to "Ожидание QR",
        "connecting" to "Подключение",
        "connected" to "Подключен",
        "running" to "Работает",
        "last_error" to "Последняя ошибка",
        "active" to "Активно",
        "uptime" to "Время работы",
        "today" to "Сегодня",
        "messages" to "Сообщения",
        "searches" to "Поиски",
        "completed" to "Завершено",
        "failed" to "Ошибки",
        "no_jobs" to "Задач пока нет.",
        "time" to "Время",
        "chat" to "Чат",
        "clear" to "Очистить",
        "whatsapp_integration" to "Интеграция WhatsApp",
        "session_saved" to "OK - сессия WhatsApp сохранена",
        "session_running" to "У бота уже есть сохраненная сессия WhatsApp, и он работает.",
        "session_disconnected" to "У бота уже есть сохраненная сессия WhatsApp. Запустите бота для подключения.",
        "session_saved_detail" to "У бота уже есть сохраненная сессия WhatsApp.",
        "pairing_intro" to "Бот подключается как реальное связанное устройство вашей личной учетной записи WhatsApp. Введите номер основного телефона и подтвердите код в WhatsApp > Связанные устройства.",
        "whatsapp_number" to "Номер WhatsApp",
        "generate_again" to "Повторить через",
        "generate_code" to "Создать код связанного устройства",
        "code" to "Код",
        "copy_code" to "Скопировать код",
        "tap_copy" to "Нажмите на код, чтобы скопировать.",
        "link_phone" to "В WhatsApp: Связанные устройства > Связать по номеру телефона.",
        "regular_messages" to "Обычные сообщения игнорируются. Бот отвечает только на команды /help, /music search, /v, /a, /status и /cancel.",
        "blacklist" to "Blocklist",
        "blacklist_desc" to "Номера из этого списка игнорируются ботом. Приложение остается подключенным к WhatsApp, но бот не ищет, не скачивает и не отвечает этим людям.",
        "blocklist_new_number" to "Номер WhatsApp",
        "add_blocklist_number" to "Добавить",
        "remove_blocklist_number" to "Удалить номер",
        "blocklist_empty" to "Заблокированных номеров пока нет.",
        "blocklist_active_numbers" to "Заблокированные номера",
        "start_boot" to "Запускать при включении телефона",
        "notifications" to "Уведомления",
        "detailed_notifications" to "Подробные уведомления",
        "system" to "Система",
        "light" to "Светлая",
        "dark" to "Темная",
        "video" to "Видео",
        "audio_type" to "Аудио",
        "queued" to "В очереди",
        "downloading" to "Загрузка",
        "processing" to "Обработка",
        "sending" to "Отправка",
        "cancelled" to "Отменено",
        "no_logs" to "Пока нет журналов бота.",
        "no_errors" to "Недавних ошибок нет."
    )
}
