package com.zapbot.android.ui

object AppStrings {
    fun label(language: String, key: String): String = when (language) {
        "pt" -> pt[key]
        "es" -> es[key]
        "ru" -> ru[key]
        else -> en[key]
    } ?: en[key] ?: key

    private val en = mapOf(
        "settings" to "Settings",
        "appearance" to "Appearance",
        "app_language" to "App language",
        "bot_language" to "Bot message language",
        "battery" to "Open battery settings",
        "downloads" to "Simultaneous downloads",
        "quality" to "Video quality",
        "audio" to "Audio",
        "clear_cache" to "Clear WhatsApp cache",
        "logs" to "Logs",
        "home" to "Home",
        "jobs" to "Jobs",
        "errors" to "Recent errors",
        "subtitle" to "WhatsApp automation console",
        "start_bot" to "Start bot",
        "stop_bot" to "Stop bot",
        "bot_status" to "Bot status",
        "disconnected" to "Disconnected",
        "waiting_qr" to "Waiting for QR code",
        "connecting" to "Connecting",
        "connected" to "Connected",
        "running" to "Running",
        "last_error" to "Last error",
        "active" to "Active",
        "uptime" to "Uptime",
        "today" to "Today",
        "messages" to "Messages",
        "searches" to "Searches",
        "completed" to "Completed",
        "failed" to "Failed",
        "no_jobs" to "No jobs created.",
        "time" to "Time",
        "chat" to "Chat",
        "clear" to "Clear",
        "whatsapp_integration" to "WhatsApp integration",
        "session_saved" to "OK - WhatsApp session saved",
        "session_running" to "This bot already has a saved WhatsApp session and is running.",
        "session_disconnected" to "This bot already has a saved WhatsApp session. Start the bot to connect.",
        "session_saved_detail" to "This bot already has a saved WhatsApp session.",
        "pairing_intro" to "This bot connects as a real linked device for your personal WhatsApp account. Enter the number from the main phone, then approve the code in WhatsApp > Linked devices.",
        "whatsapp_number" to "WhatsApp number",
        "generate_again" to "Generate again in",
        "generate_code" to "Generate Linked Devices code",
        "code" to "Code",
        "copy_code" to "Copy code",
        "tap_copy" to "Tap the code to copy it.",
        "link_phone" to "In WhatsApp: Linked devices > Link with phone number.",
        "regular_messages" to "Regular messages are ignored silently. The bot only replies to slash commands such as /help, /music search, /v, /a, /status, and /cancel.",
        "start_boot" to "Start when the phone boots",
        "notifications" to "Notifications",
        "detailed_notifications" to "Detailed notifications",
        "system" to "System",
        "light" to "Light",
        "dark" to "Dark",
        "video" to "Video",
        "audio_type" to "Audio",
        "queued" to "Queued",
        "downloading" to "Downloading",
        "processing" to "Processing",
        "sending" to "Sending",
        "cancelled" to "Cancelled",
        "no_logs" to "No bot logs yet.",
        "no_errors" to "No recent errors."
    )
    private val pt = mapOf(
        "settings" to "Ajustes",
        "appearance" to "Aparência",
        "app_language" to "Idioma do aplicativo",
        "bot_language" to "Idioma das mensagens do bot",
        "battery" to "Abrir configurações de bateria",
        "downloads" to "Downloads simultâneos",
        "quality" to "Qualidade do vídeo",
        "audio" to "Áudio",
        "clear_cache" to "Limpar cache do WhatsApp",
        "logs" to "Logs",
        "home" to "Início",
        "jobs" to "Tarefas",
        "errors" to "Erros recentes",
        "subtitle" to "Painel de automação do WhatsApp",
        "start_bot" to "Iniciar bot",
        "stop_bot" to "Parar bot",
        "bot_status" to "Status do bot",
        "disconnected" to "Desconectado",
        "waiting_qr" to "Aguardando QR code",
        "connecting" to "Conectando",
        "connected" to "Conectado",
        "running" to "Rodando",
        "last_error" to "Último erro",
        "active" to "Ativos",
        "uptime" to "Tempo online",
        "today" to "Hoje",
        "messages" to "Mensagens",
        "searches" to "Buscas",
        "completed" to "Concluídos",
        "failed" to "Falhas",
        "no_jobs" to "Nenhuma tarefa criada.",
        "time" to "Hora",
        "chat" to "Chat",
        "clear" to "Limpar",
        "whatsapp_integration" to "Integração do WhatsApp",
        "session_saved" to "OK - sessão do WhatsApp salva",
        "session_running" to "Este bot já tem uma sessão do WhatsApp salva e está rodando.",
        "session_disconnected" to "Este bot já tem uma sessão do WhatsApp salva. Inicie o bot para conectar.",
        "session_saved_detail" to "Este bot já tem uma sessão do WhatsApp salva.",
        "pairing_intro" to "Este bot conecta como um aparelho vinculado real da sua conta pessoal do WhatsApp. Digite o número do celular principal e aprove o código em WhatsApp > Aparelhos conectados.",
        "whatsapp_number" to "Número do WhatsApp",
        "generate_again" to "Gerar novamente em",
        "generate_code" to "Gerar código de Aparelhos conectados",
        "code" to "Código",
        "copy_code" to "Copiar código",
        "tap_copy" to "Toque no código para copiar.",
        "link_phone" to "No WhatsApp: Aparelhos conectados > Conectar com número de telefone.",
        "regular_messages" to "Mensagens normais são ignoradas silenciosamente. O bot responde apenas a comandos como /help, /music search, /v, /a, /status e /cancel.",
        "start_boot" to "Iniciar quando o celular ligar",
        "notifications" to "Notificações",
        "detailed_notifications" to "Notificações detalhadas",
        "system" to "Sistema",
        "light" to "Claro",
        "dark" to "Escuro",
        "video" to "Vídeo",
        "audio_type" to "Áudio",
        "queued" to "Na fila",
        "downloading" to "Baixando",
        "processing" to "Processando",
        "sending" to "Enviando",
        "cancelled" to "Cancelado",
        "no_logs" to "Nenhum log do bot ainda.",
        "no_errors" to "Nenhum erro recente."
    )
    private val es = mapOf(
        "settings" to "Ajustes",
        "appearance" to "Apariencia",
        "app_language" to "Idioma de la app",
        "bot_language" to "Idioma de mensajes del bot",
        "battery" to "Abrir ajustes de batería",
        "downloads" to "Descargas simultáneas",
        "quality" to "Calidad de video",
        "audio" to "Audio",
        "clear_cache" to "Limpiar caché de WhatsApp",
        "logs" to "Registros",
        "home" to "Inicio",
        "jobs" to "Tareas",
        "errors" to "Errores recientes",
        "subtitle" to "Panel de automatización de WhatsApp",
        "start_bot" to "Iniciar bot",
        "stop_bot" to "Detener bot",
        "bot_status" to "Estado del bot",
        "disconnected" to "Desconectado",
        "waiting_qr" to "Esperando QR",
        "connecting" to "Conectando",
        "connected" to "Conectado",
        "running" to "Activo",
        "last_error" to "Último error",
        "active" to "Activos",
        "uptime" to "Tiempo activo",
        "today" to "Hoy",
        "messages" to "Mensajes",
        "searches" to "Búsquedas",
        "completed" to "Completados",
        "failed" to "Fallos",
        "no_jobs" to "No hay tareas creadas.",
        "time" to "Hora",
        "chat" to "Chat",
        "clear" to "Limpiar",
        "whatsapp_integration" to "Integración de WhatsApp",
        "session_saved" to "OK - sesión de WhatsApp guardada",
        "session_running" to "Este bot ya tiene una sesión de WhatsApp guardada y está activo.",
        "session_disconnected" to "Este bot ya tiene una sesión de WhatsApp guardada. Inicia el bot para conectar.",
        "session_saved_detail" to "Este bot ya tiene una sesión de WhatsApp guardada.",
        "pairing_intro" to "Este bot se conecta como un dispositivo vinculado real de tu cuenta personal de WhatsApp. Ingresa el número del teléfono principal y aprueba el código en WhatsApp > Dispositivos vinculados.",
        "whatsapp_number" to "Número de WhatsApp",
        "generate_again" to "Generar de nuevo en",
        "generate_code" to "Generar código de dispositivos vinculados",
        "code" to "Código",
        "copy_code" to "Copiar código",
        "tap_copy" to "Toca el código para copiarlo.",
        "link_phone" to "En WhatsApp: Dispositivos vinculados > Vincular con número de teléfono.",
        "regular_messages" to "Los mensajes normales se ignoran silenciosamente. El bot solo responde a comandos como /help, /music search, /v, /a, /status y /cancel.",
        "start_boot" to "Iniciar al encender el teléfono",
        "notifications" to "Notificaciones",
        "detailed_notifications" to "Notificaciones detalladas",
        "system" to "Sistema",
        "light" to "Claro",
        "dark" to "Oscuro",
        "video" to "Video",
        "audio_type" to "Audio",
        "queued" to "En cola",
        "downloading" to "Descargando",
        "processing" to "Procesando",
        "sending" to "Enviando",
        "cancelled" to "Cancelado",
        "no_logs" to "Aún no hay registros del bot.",
        "no_errors" to "No hay errores recientes."
    )
    private val ru = mapOf(
        "settings" to "Настройки",
        "appearance" to "Внешний вид",
        "app_language" to "Язык приложения",
        "bot_language" to "Язык сообщений бота",
        "battery" to "Открыть настройки батареи",
        "downloads" to "Одновременные загрузки",
        "quality" to "Качество видео",
        "audio" to "Аудио",
        "clear_cache" to "Очистить кэш WhatsApp",
        "logs" to "Журналы",
        "home" to "Главная",
        "jobs" to "Задачи",
        "errors" to "Последние ошибки",
        "subtitle" to "Панель автоматизации WhatsApp",
        "start_bot" to "Запустить бот",
        "stop_bot" to "Остановить бот",
        "bot_status" to "Статус бота",
        "disconnected" to "Отключен",
        "waiting_qr" to "Ожидание QR",
        "connecting" to "Подключение",
        "connected" to "Подключен",
        "running" to "Работает",
        "last_error" to "Последняя ошибка",
        "active" to "Активно",
        "uptime" to "Время работы",
        "today" to "Сегодня",
        "messages" to "Сообщения",
        "searches" to "Поиски",
        "completed" to "Завершено",
        "failed" to "Ошибки",
        "no_jobs" to "Задач пока нет.",
        "time" to "Время",
        "chat" to "Чат",
        "clear" to "Очистить",
        "whatsapp_integration" to "Интеграция WhatsApp",
        "session_saved" to "OK - сессия WhatsApp сохранена",
        "session_running" to "У бота уже есть сохраненная сессия WhatsApp, и он работает.",
        "session_disconnected" to "У бота уже есть сохраненная сессия WhatsApp. Запустите бота для подключения.",
        "session_saved_detail" to "У бота уже есть сохраненная сессия WhatsApp.",
        "pairing_intro" to "Бот подключается как реальное связанное устройство вашей личной учетной записи WhatsApp. Введите номер основного телефона и подтвердите код в WhatsApp > Связанные устройства.",
        "whatsapp_number" to "Номер WhatsApp",
        "generate_again" to "Повторить через",
        "generate_code" to "Создать код связанного устройства",
        "code" to "Код",
        "copy_code" to "Скопировать код",
        "tap_copy" to "Нажмите на код, чтобы скопировать.",
        "link_phone" to "В WhatsApp: Связанные устройства > Связать по номеру телефона.",
        "regular_messages" to "Обычные сообщения игнорируются. Бот отвечает только на команды /help, /music search, /v, /a, /status и /cancel.",
        "start_boot" to "Запускать при включении телефона",
        "notifications" to "Уведомления",
        "detailed_notifications" to "Подробные уведомления",
        "system" to "Система",
        "light" to "Светлая",
        "dark" to "Темная",
        "video" to "Видео",
        "audio_type" to "Аудио",
        "queued" to "В очереди",
        "downloading" to "Загрузка",
        "processing" to "Обработка",
        "sending" to "Отправка",
        "cancelled" to "Отменено",
        "no_logs" to "Пока нет журналов бота.",
        "no_errors" to "Недавних ошибок нет."
    )
}
